### ISSUE TITLE
Pretty serious performance issues under OS X

### ISSUE THREAD

**Issue by psfblair** [ionide/ionide-atom-fsharp#240] opened 2016-06-10 01:38 UTC
Once every 15 minutes or so I'm navigating a file and the Atom editor freezes up. After a minute or two I get a dialog that says the editor is not responding, and asks me if I want to keep waiting or close the window. If I close the window, it generally behaves. If I keep waiting, it stays hung until the next time the dialog opens (which is a longer interval) and if I close the window at that point Atom crashes.

Here is the project I'm working with - the .fsproj file in the following directory: https://github.com/fsprojects/Fable/tree/master/import

Some of these files are reasonably big, but right now they're all but impossible to work with.

Visual Studio Code has similar issues, though it pauses for less time and then recovers.

**Comment by Krzysztof-Cieslak** [comment] 2016-07-20 21:19
Can't reproduce on my test machine, closing for now - until better reproduction is provided.

**Closed by Krzysztof-Cieslak** 2016-07-20 21:19 UTC
Labels: no-reproduction
